name: pre-commit
description: 'Run pre-commit tasks'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
    type: string
  working_directory:
    description: 'Working directory for pre-commit checks'
    required: false
    default: '.'
  pre-commit-tasks:
    description: 'Comma separated list of tasks to run, or single task name'
    required: true
runs:
  using: 'composite'
  steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install pre-commit
        shell: bash
        working-directory: ${{ inputs.working_directory }}

      - name: Run pre-commit
        run: |
          IFS=',' read -ra TASK_NAMES <<< "${{ inputs.pre-commit-tasks }}"

          for task in "${TASK_NAMES[@]}"; do
            task="$(echo "$task" | xargs)"  # trim whitespace

            if [[ -z "$task" ]]; then
              echo "Empty pre-commit task detected" >&2
              exit 1
            fi

            echo "Running pre-commit task: $task"
            pre-commit run --all-files "$task"
          done
        shell: bash
        working-directory: ${{ inputs.working_directory }}
