name: 'Wrap IAM Policies'
description: 'Generate CloudFormation wrappers for IAM policy template files'
inputs:
  policy_directory:
    description: 'Directory containing policy files to wrap'
    required: false
    default: 'terraform/policies'
  working_directory:
    description: 'Working directory for action'
    required: false
    default: '.'
runs:
  using: 'composite'
  defaults:
    run:
      shell: bash
      working-directory: ${{ inputs.terraform_dir }}
  steps:
    - name: Generate Policy Wrappers
      run: bash ${{ github.action_path }}/scripts/generate-policy-wrappers.sh "${{ inputs.policy_directory }}"